FROM node:20.11-slim

WORKDIR /app

# 安裝你現在真正需要的 dev tools
RUN apt-get update && apt-get install -y \
    postgresql-client \
    supervisor \
    python3 \
    && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV=development

RUN npx prisma generate

COPY supervisord.conf /etc/supervisord.conf

EXPOSE 3001 5555

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
