import express from "express";
import {
  generateReport,
  getReportByResponseId,
  addReportImage,
} from "../controllers/reportController";

const router = express.Router();

/**
 * @openapi
 * components:
 *   schemas:
 *     TAIReportRadarItem:
 *       type: object
 *       properties:
 *         axis:
 *           type: string
 *           example: Accuracy
 *         value:
 *           type: number
 *           format: float
 *           example: 0.82
 *
 *     TAIReport:
 *       type: object
 *       properties:
 *         responseId:
 *           type: integer
 *           example: 12
 *         radarData:
 *           type: array
 *           description: Radar data for frontend visualization (0–1 range)
 *           items:
 *             $ref: '#/components/schemas/TAIReportRadarItem'
 *         scores:
 *           type: object
 *           description: Per-axis average score (0–1)
 *           additionalProperties:
 *             type: number
 *             format: float
 *           example:
 *             Accuracy: 0.82
 *             Safety: 0.65
 *             Reliability: 0.90
 *         overallScore:
 *           type: number
 *           format: float
 *           description: Mean of all axis scores (0–1)
 *           example: 0.79
 *         analysisText:
 *           type: string
 *           description: Natural language analysis generated by LLM
 *           example: >
 *             整體而言，本次 AI 系統在準確性與可靠性方面表現良好，但在隱私與公平性仍有待加強...
 *
 *     SuccessResponse_TAIReport:
 *       type: object
 *       properties:
 *         success:
 *           type: boolean
 *           example: true
 *         data:
 *           $ref: '#/components/schemas/TAIReport'
 *         message:
 *           type: string
 *           nullable: true
 *           example: null
 *
 *     ErrorResponse:
 *       type: object
 *       properties:
 *         success:
 *           type: boolean
 *           example: false
 *         error:
 *           type: object
 *           properties:
 *             message:
 *               type: string
 *               example: Something went wrong
 */

/**
 * @openapi
 * /api/report/generate/{responseId}:
 *   post:
 *     summary: Generate a TAI report from a specific response
 *     description: >
 *       根據指定的 responseId，讀取問卷作答內容，計算各 TAI 指標分數（0–1），
 *       並呼叫 LLM 生成綜合分析文字。此 API **不會**在資料庫中新增或更新 report 資料，
 *       僅即時計算並回傳結果給前端。
 *     tags: [Report]
 *     parameters:
 *       - in: path
 *         name: responseId
 *         required: true
 *         schema:
 *           type: integer
 *         description: ID of the response to generate report from
 *     responses:
 *       201:
 *         description: Report generated successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SuccessResponse_TAIReport'
 *       400:
 *         description: Invalid responseId
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       404:
 *         description: Response not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       500:
 *         description: Internal server error or LLM failure
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.post("/generate/:responseId", generateReport);


/**
 * @openapi
 * /api/report/response/{responseId}:
 *   get:
 *     summary: "Legacy - Get a stored report by responseId"
 *     description: >
 *       **Legacy API**：若系統有將 report 寫入資料庫，可透過 responseId 讀回。
 *       若目前系統不再儲存報告，此端點可以標記為 deprecated 或移除。
 *     tags: [Report]
 *     parameters:
 *       - in: path
 *         name: responseId
 *         required: true
 *         schema:
 *           type: integer
 *         description: Response ID associated with the stored report
 *     responses:
 *       200:
 *         description: Stored report found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               description: Wrap of Prisma report entity (implementation-specific)
 *       404:
 *         description: Report not found for this response
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.get("/response/:responseId", getReportByResponseId);


/**
 * @openapi
 * /api/report/{reportId}/image:
 *   post:
 *     summary: "Legacy - Add an image to a stored report"
 *     description: >
 *       **Legacy / Optional API**：當系統有將報告存入資料庫，且需要上傳補充圖像時使用。
 *       若目前不再將 report 與 image 存入 DB，可將此端點標記為 deprecated 或移除。
 *     tags: [Report]
 *     parameters:
 *       - in: path
 *         name: reportId
 *         required: true
 *         schema:
 *           type: integer
 *         description: ID of the stored report
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - url
 *             properties:
 *               url:
 *                 type: string
 *                 description: Public URL of the image
 *                 example: https://example.com/report-image.png
 *               caption:
 *                 type: string
 *                 nullable: true
 *                 example: Radar chart of TAI scores
 *     responses:
 *       201:
 *         description: Image added to report successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               description: Wrap of Prisma reportImage entity (implementation-specific)
 *       400:
 *         description: Missing or invalid fields (e.g., url)
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       404:
 *         description: Report not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.post("/:reportId/image", addReportImage);

export default router;
